[project]
name = 'Supply-Chain-Quality-Assurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.product-specification]
path = 'contracts/product-specification.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-performance]
path = 'contracts/supplier-performance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
